config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end


  root to: "homes#top"

  get "home/about"=>"homes#about"

  get "search" => "searches#search"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get "search_form" => "users#search"
  end

  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]

  resources :groups do
    get "join"=> "groups#join"
  end

  resources :contacts, only: [:new, :create, :show]

  get 'search_book' => 'books#search_book'



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_one_attached :profile_image
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  #フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy #1
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy #3
  #一覧画面で使う
  has_many :followings, through: :relationships, source: :followed #2
  has_many :followers, through: :reverse_of_relationships, source: :follower #4

  #DM機能のアソシエーション
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  #閲覧機能のアソシエーション
  has_many :view_counts, dependent: :destroy

  #グループ機能
  has_many :group_users
  has_many :groups, through: :group_users

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true , presence: true
  validates :introduction, length: { maximum: 50 }

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?","#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  def self.guest
    find_or_create_by!(name: 'guestuser', email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: 'guestuserでログインしました。'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]
  before_action :ensure_guest_user, only: [:edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    #ここからDM機能
    @currentUserEntry = Entry.where(user_id: current_user.id)#ログインしているユーザーと
    @userEntry = Entry.where(user_id: @user.id)#メッセージ相手のユーザをEntryテーブルから検索して取得している
    unless @user.id == current_user.id#ログインしていないユーザーという条件をつける
      @currentUserEntry.each do |cu|#①
        @userEntry.each do |u|#②→①と②でさっき取得した２つのユーザーをそれぞれeachで取り出して
          if cu.room_id == u.room_id then#ログインユーザーと相手ユーザーのroom_idが一緒だったらという条件指定
            @isRoom = true#Entryテーブル内に同じroom_idが共通しているユーザー同士に対して
            @roomId = cu.room_id#@roomId=cu.room_idという変数を指定する
          end
        end
      end
      unless @isRoom#@isRoomがfalseの時
        @room = Room.new#新しくインスタンスを生成するために.newと記載
        @entry = Entry.new
      end
    end
    #投稿数カウント
    @today_book = @books.created_today
    @yesterday_book = @books.created_yesterday
    @this_week_book = @books.created_this_week
    @last_week_book = @books.created_last_week
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      @books = @user.books
      render "edit"
    end
  end

  def search
    @user = User.find(params[:user_id])
    @books = @user.books
    @book = Book.new
    if params[:created_at] == ""
      @search_book = "日付を選択してください"
    else
      create_at = params[:created_at]
      @search_book = @books.where(['created_at LIKE ? ', "#{create_at}%"]).count
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

  def ensure_guest_user
    @user = User.find(params[:id])
    if @user.name == "guestuser"
      redirect_to user_path(current_user), notice: 'ゲストユーザーはプロフィール編集画面へ遷移できません。'
    end
  end

end

app/helpers/user/sessions_helper.rb
module User::SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_day-search.html.erb
<h4>検索結果</h4>
  <table class='table table-bordered'>
    <thead>
      <tr>
        <th>投稿数</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= search_book %></td>
      </tr>
    </tbody>
  </table>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>
          <p>フォロー数：<%= user.followings.count %></p>
        </td>
        <td>
          <p>フォロワー数：<%= user.followers.count %></p>
        </td>
        <% if user != current_user %>
          <% if current_user.following?(user) %>
            <td><%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %></td>
          <% else %>
            <td><%= link_to "フォローする", user_relationships_path(user.id), method: :post %></td>
          <% end %>
        <% else %>
        <td></td>
        <% end %>
        <td><%= link_to 'Show', user %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th>
      <%= link_to user_followings_path(user.id) do %>
        <%= user.followings.count %>
      <% end %>
    </th>
  </tr>
  <tr>
    <th>followers</th>
    <th>
      <%= link_to user_followers_path(user.id) do %>
        <%= user.followers.count %>
      <% end %>
    </th>
  </tr>
</table>

<div class='row'>
  <% if user.name != "guestuser" %>

    <% if user != current_user %>
      <% if current_user.following?(user) %>
        <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-sm btn-info" %>

        <% if isRoom == true %>
          <p><%= kink_to 'chatを始める', room_path(roomId) %></p>
        <% else %>
          <%= form_with model:room, url: rooms_path, method: :post do |f| %>
            <%= fields_for entry do |e| %>
              <%= e.hidden_field :user_id, value: user.id %>
            <% end %>
            <%= f.submit "chatを開始する" %>
          <% end %>
        <% end %>

      <% else %>
        <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-sm btn-success" %>
      <% end %>
    <% else %>
      <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
    <% end %>

  <% end %>

</div>

app/views/users/_post-count.html.erb
<h3>投稿数の前日比・前週比</h3>
<div class = "table_width">
  <table class = "table table-bordered">
    <thead>
      <tr>
        <th>今日の投稿数</th>
        <th>前日の投稿数</th>
        <th>前日比</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= today_book.count %></td>
        <td><%= yesterday_book.count %></td>

          <% if yesterday_book.count == 0 %>
            <td>前日の投稿はありません</td>
          <% else %>
            <td>
              <% the_day_before = today_book.count / yesterday_book.count.to_f %>
              <%= (the_day_before * 100).round %>
            </td>
          <% end %>

      </tr>
    </tbody>
  </table>
</div>

<div class = "table_width">
  <table class = "table table-bordered">
    <thead>
      <tr>
        <th>今週の投稿</th>
        <th>先週の投稿</th>
        <th>前週比</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= this_week_book.count %></td>
        <td><%= last_week_book.count %></td>
        <% if last_week_book.count == 0 %>
          <td>先週の投稿はありません</td>
        <% else %>
          <td>
            <% the_week_before = this_week_book.count / last_week_book.count.to_f  %>
       　    <%= (the_week_before * 100).round %>
       　  </td>
        <% end %>
       </tr>
    </tbody>
  </table>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'info', user: current_user, isRoom: @isRoom, roomId: @roomId, room: @room, entry: @entry %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
      <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <div>
        <%= link_to 'グループを作成する', new_group_path %>
        |
        <%= link_to 'グループ一覧', groups_path %>
      </div>
      <%= render 'index',users: @users %>
    </div>
  </div>
  <%= month_calendar do |date| %>
    <%= date %>
  <% end %>
</div>

app/views/users/search.js.erb
$("#search_result").html("<%= j(render 'day-search', search_book: @search_book) %>");

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>

      <h2>User info</h2>
      <%= render 'info', user: @user, isRoom: @isRoom, roomId: @roomId, room: @room, entry: @entry %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>

    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index', books: @books %>
      <%= render 'post-count' , today_book: @today_book, yesterday_book: @yesterday_book, this_week_book: @this_week_book, last_week_book: @last_week_book %>
      <%= form_with url: user_search_form_path(@user.id), method: :get, local: false do |f| %>
        <%= f.date_field :created_at %>
        <%= f.submit '検索', class: 'btn btn-primary' %>
      <% end %>
      <div id="search_result">
        <% if @search_book.present? %>
          <%= render 'day-search', search_book: @search_book %>
        <% end %>
      </div>
    </div>
  </div>
</div>